services:
  client:
    image: client-dev-image
    build:
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./client:client
      - node_modules:/client/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
